<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner signature="Workspace" version="12.5.0.2169"?>
<!-- do not edit this file -->

<Workspace>
	<Local Expanded="Yes">
		<Model Expanded="Yes" ID="{E56B9DE4-E384-4D29-8C33-B5315A1945DC}" Name="${project.name}" Selected="Yes" Type="{CDE44E21-9669-11D1-9914-006097355D9B}" URL="${project.name}.pdm"/>
	</Local>
	<BrowserModule Name="Repository"/>
</Workspace>
