<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE taglib PUBLIC "-//Sun Microsystems, Inc.//DTD JSP Tag Library 1.2//EN" "http://java.sun.com/dtd/web-jsptaglibrary_1_2.dtd">
<taglib>
	<tlib-version>2.2.3</tlib-version>
	<jsp-version>1.2</jsp-version>
  	<short-name>cs</short-name>
  	<uri>/custom-struts-tags</uri>
  	<display-name>"custom struts Tags"</display-name>
    <tag>
        <name>page</name>
        <tagclass>${project.org}.tool.tags.PageTag</tagclass>
        <bodycontent>empty</bodycontent>
        <attribute>
            <name>value</name>
            <required>true</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>pageNum</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
        <attribute>
            <name>model</name>
            <required>false</required>
            <rtexprvalue>true</rtexprvalue>
        </attribute>
    </tag>
    <tag>
        <name>substring</name>
        <tag-class>${project.org}.tool.tags.SubStringTag</tag-class>
   		<body-content>empty</body-content>
	    <attribute>
	      <name>default</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>escape</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>id</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>value</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>tail</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>length</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>rowCount</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
	    <attribute>
	      <name>rowLength</name>
	      <required>false</required>
	      <rtexprvalue>false</rtexprvalue>
	    </attribute>
    </tag>
</taglib>